<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>上传fcup</title>
</head>
<body>
<div style="padding: 10px;">
    <div style="margin-bottom: 40px;">
        <p>:普通文件上传</p>
        <button class="start_upload">普通文件上传</button>
        <div class="info" style="margin-top: 20px;"></div>
    </div>
    <div style="margin-bottom: 40px;">
        <p>:大文件分片上传</p>
        <button id="start_upload1">大文件分片上传</button>
        <div class="info" style="margin-top: 20px;"></div>
    </div>

</div>

</body>
<script src="/js/upload/jquery.min.js"></script>
<script src="/js/upload/fcupUpload.js"></script>
<script>
    //upShardSize,upMaxSize,upType,serverUrl,project,fcupUploadCallback
    // upShardSize 切片大小,
    // (单次上传最大值)单位M,upMaxSize,传文件大小,单位M，不设置不限制，
    // upType 文件上传类型,
    // serverUrl 环境地址 必传，（在该demo项目不传默认项目路径）
    // project 项目名称 不传默认upload目录
    $(".start_upload").click(function () {
        var click = $(this);
        fcupUpload.fcupInit("1","2","jpg,png,gif","","demo",function (data) {
            var info = '文件地址：'+data.url+'；文件名：'+data.name;
            click.parent().find(".info").html(info);
        });
    });
    $("#start_upload1").click(function () {
        var click = $(this);
        fcupUpload.fcupInit("10","","","","",function (data) {
            var info = '文件地址'+data.url+'；文件名：'+data.name;
            click.parent().find(".info").html(info);
        });
    });
</script>


</html>